directories:
  output: dist
  buildResources: resources
publish:
  - provider: generic
    url: 'https://umbrellanote.com/updates'
appId: com.umbrellanote.arban
productName: Umbrella Note
copyright: 'copyright © 2018, Arpit Bansal'
mac:
  category: public.app-category.productivity
  target:
    - zip
    - dmg
files:
  - app/**/*
  - node_modules/**/*
  - package.json
dmg:
  title: Umbrella Note
  contents:
    - x: 110
      'y': 150
    - x: 240
      'y': 150
      type: link
      path: /Applications
linux:
  category: Office
  target:
    - target: tar.gz
      arch:
        - x64
        - ia32
    - target: deb
      arch:
        - x64
        - ia32
  icon: resources/umbrella.png
win:
  target:
    - target: nsis
      arch:
        - x64
        - ia32
  icon: resources/icon.ico
electronVersion: 1.6.17
